name: Publish Website to CPanel
on:
  push:
    branches:
      - console

jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          protocol: ftps
          local-dir: dist/console-panel/browser/
          server-dir: ${{ secrets.CONSOLE_REMOTE_DIR }}
          dangerous-clean-slate: false
          git-ftp-args: --force