name: Deploy Stage

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Frontend (Stage)
        run: npx ng build frontend --configuration web-production --base-href https://safure.demohandler.in/

      - name: Build Console (Stage)
        run: npx ng build console-panel --configuration console-production --base-href https://console.demohandler.in/

      - name: Verify Build Output
        run: |
          ls -R dist/frontend/browser/
          ls -R dist/console-panel/browser/

      - name: Deploy Frontend to Stage
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER_STAGE }}
          username: ${{ secrets.FTP_USERNAME_STAGE }}
          password: ${{ secrets.FTP_PASSWORD_STAGE }}
          port: 22  # This is the magic port that bypasses the firewall
          local_path: './dist/frontend/browser/*' 
          remote_path: ${{ secrets.FTP_REMOTE_PATH_STAGE }}
      - name: Deploy Console to Stage
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER_STAGE }}
          username: ${{ secrets.FTP_USERNAME_STAGE }}
          password: ${{ secrets.FTP_PASSWORD_STAGE }}
          port: 22  # Must be 22 for SFTP
          local_path: './dist/console-panel/browser/*'
          remote_path: ${{ secrets.FTP_CONSOLE_REMOTE_PATH_STAGE }}