name: Deploy Stage

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Frontend (Stage)
        run: npx ng build frontend --configuration web-farming

      - name: Build Console (Stage)
        run: npx ng build console-panel --configuration console-farming

      - name: Deploy Frontend to Stage
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_STAGE }}
          username: ${{ secrets.FTP_USERNAME_STAGE }}
          password: ${{ secrets.FTP_PASSWORD_STAGE }}
          port: 21
          protocol: ftp
          local-dir: ./dist/frontend/browser/
          server-dir: ${{ secrets.FTP_REMOTE_PATH_STAGE }}
          exclude: |
            **/.htaccess
            console/

      - name: Deploy Console to Stage
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_STAGE }}
          username: ${{ secrets.FTP_USERNAME_STAGE }}
          password: ${{ secrets.FTP_PASSWORD_STAGE }}
          port: 21
          protocol: ftp
          local-dir: ./dist/console-panel/browser/
          server-dir: ${{ secrets.FTP_REMOTE_PATH_STAGE }}console/
          exclude: |
            **/.htaccess
